### PR TITLE
Fix some filtering and file listing bugs

### LINKED ISSUE #251: Resetting filter doesn't reset pager
With a filter applied, pressing `ESC` resets the filter. It doesn't however reset the pager's state, limiting the amount of visible items.

### PR DESCRIPTION
**Pull request by meowgorithm**
* Fix pagination when resetting the filter
* Fix inconsistencies when switching between dot and Arabic pager types

Closes #251.

### CODE REVIEW

File: ui/stash.go [hunk 1]
```diff
@@ -64,6 +64,14 @@ const (
 	stashStateShowingError
 )
 
+func (s stashViewState) String() string {
```
Comment (muesli) [inline ui/stash.go:67]: Are these `String` functions actually used somewhere yet? I think we may be able to use them to clean up the code a bit.

Comment (meowgorithm) [reply ui/stash.go:67]: I use them in debugging (in fact I used some of them to debug this). I had taken them out at one point, but since I’ve added them back I figured I’d keep them around. Been back and forth about them, though, and they do have the potential for rot, which is an argument to remove them.

Comment (meowgorithm) [reply ui/stash.go]: Alright, dropped 'em. Let's keep this code lean.
