### PR TITLE
fix: check other possible readme paths/branches

### LINKED ISSUE #434: `glow github.com/owner/repo` doesn't work with lowercase "readme.md" file
`glow https://github.com/danielwerg/r6api.js` returns `Error: can't find README in GitHub repository`

Looks like it is because glow looks strictly for `README` and `README.md` and nothing else.
https://github.com/charmbracelet/glow/blob/d9bf3b8ee89072cdec42af6d938a1bef0393c748/main.go#L31
Could it be solved by just adding `readme.md` to that ^ list?

### PR DESCRIPTION
**Pull request by caarlos0**
closes #434

also check main (as well as master) branches

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -28,14 +28,15 @@ var (
...
 
-	readmeNames  = []string{"README.md", "README"}
-	configFile   string
-	pager        bool
-	style        string
-	width        uint
-	showAllFiles bool
-	localOnly    bool
-	mouse        bool
+	readmeNames    = []string{"README.md", "README", "readme.md", "readme"}
```
Comment (danielwerg) [inline main.go:31]: What about https://gitlab.com/terrakok/gitlab-client?

Comment (caarlos0) [reply main.go:31]: oh, "Readme.md" is quite common, too, indeed
